### ISSUE TITLE
Update appreciated

### ISSUE THREAD

**Issue by dsreitan** [Geta/Epi.IndexContentInFind#1]
Installed this today, but it doesn't seem to do anything. No extra items in the Tools dropdown. Perhaps due to Structuremap changes in Epi?

**Comment by Sebbe** [comment]
@dsreitan did you look at the right place? (in the all properties view and the tool button? (see screenshot in the readme)

**Comment by frederikvig** [comment]
Can this issue be closed?

**Comment by dsreitan** [comment]
Thanks for your help 👍
